# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wiretrustee < Formula
  desc "Wiretrustee project."
  homepage "https://wiretrustee.com/"
  version "0.1.0-rc-14"
  license "BSD3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mlsmaycon/wiretrustee/releases/download/v0.1.0-rc-14/wiretrustee_0.1.0-rc-14_darwin_amd64.zip", :using => CurlDownloadStrategy
      sha256 "ae7382a2608a5c149a2a6d6b8fe77524c38d9854f509aaefa77e0d02089de1e4"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mlsmaycon/wiretrustee/releases/download/v0.1.0-rc-14/wiretrustee_0.1.0-rc-14_linux_amd64.zip", :using => CurlDownloadStrategy
      sha256 "5bbb6255c99567741965aef7b55cb3c88b587d4bc61612f20e1f25d35efce471"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mlsmaycon/wiretrustee/releases/download/v0.1.0-rc-14/wiretrustee_0.1.0-rc-14_linux_armv6.zip", :using => CurlDownloadStrategy
      sha256 "ef996ec7d0344bbc3483468faeefaca577f3200b4806f42debd6a8ad58bb46d8"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mlsmaycon/wiretrustee/releases/download/v0.1.0-rc-14/wiretrustee_0.1.0-rc-14_linux_arm64.zip", :using => CurlDownloadStrategy
      sha256 "9f28f636c0b5e1d4589de565400559dd44384be2f81b6f1323ebb8593871629d"
    end
  end

  def install
    bin.install "wiretrustee"
  end

  test do
    system "#{bin}/wiretrustee -h"
  end
end
